INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (1, '2020-05-21 23:54:37.377000', '2020-05-21 23:54:39.994000', 'Vitor Emanoel', 0);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (2, null, null, 'Geraldo Henry Castro', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (3, null, null, 'Levi Breno Rocha', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (4, null, null, 'Ayla Luzia Larissa Carvalho', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (5, null, null, 'Daiane Clara Dias', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (6, null, null, 'Emily Regina da Silva', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (7, null, null, 'Erick Raul Galvão', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (8, null, null, 'Cauê Carlos Thiago Porto', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (9, null, null, 'Daniela Mariah Lopes', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (10, null, null, 'Juliana Natália Antonella Nogueira', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (11, null, null, 'Rosa Maria Isis Alves', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (12, null, null, 'Milena Bárbara Eliane Rodrigues', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (13, null, null, 'Anthony Yuri Murilo Baptista', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (14, null, null, 'Kamilly Isabelly da Mota', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (15, null, null, 'Oliver Leonardo Breno dos Santos', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (16, null, null, 'Lucas Cláudio Almeida', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (17, null, null, 'Simone Raquel Yasmin Gonçalves', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (18, null, null, 'Louise Raimunda Duarte', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (19, null, null, 'Lucca Oliver Cardoso', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (20, null, null, 'Ian Murilo Porto', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (21, null, null, 'Pietro Davi Fogaça', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (22, null, null, 'Luzia Sophia Ferreira', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (23, null, null, 'Breno Matheus Iago Nascimento', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (24, null, null, 'Mário Paulo Julio Duarte', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (25, null, null, 'Isabella Cláudia Emanuelly Pires', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (26, null, null, 'Henry Kaique de Paula', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (27, null, null, 'Gael Lucas Assunção', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (28, null, null, 'Iago Cláudio da Conceição', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (29, null, null, 'Benedita Antônia da Costa', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (30, null, null, 'Natália Aparecida Francisca Duarte', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (31, null, null, 'Guilherme Mário Aragão', null);
INSERT INTO vitor.clients (id, created_at, updated_at, name, type) VALUES (32, '2020-06-03 13:54:53.666803', '2020-06-03 13:54:53.666803', '', 0);